### ISSUE TITLE
Delete mail with Greemail deployed as a web service/application

### ISSUE THREAD

**Issue by cgaulay** [greenmail-mail-test/greenmail#131] opened 2016-04-26 15:37 UTC
Hi all, 

is there any way to delete a message on a greenmail server when he's deployed as a web service/application ? 

I try to set deleted flag on the message and close folder with expunge option but it doesn't work.
The message is still present.

Have you any idea ? 
Thanks.

Regards

**Comment by marcelmay** [comment] 2016-04-27 05:09
See [ImapServerTest#testExpunge](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/test/ImapServerTest.java#L421)

**Comment by buildscientist** [comment] 2016-05-11 04:58
@cgaulay I tested deletes on both POP3 and IMAP accounts and they work fine with GreenMail deployed via a webapp. 

Closing as I am unable to reproduce this.

**Closed by buildscientist** 2016-05-11 04:58 UTC
Labels: question
