### ISSUE TITLE
ImapHostManager returns 2 messages and greenmail.getReceivedMessages return none

### ISSUE THREAD

**Issue by mhiemstrapodiumtv** [greenmail-mail-test/greenmail#93] opened 2015-08-25 13:43 UTC
I am experiencing a serious issue with greenmail. I setup greenmail to receive emails on port 2525 and in my code I send an email to that port using apache email project. The emails are sent. 

My code to startup greenmail is this:
```
ServerSetup serverSetup = new ServerSetup ( 2525, "localhost", ServerSetup.PROTOCOL_SMTP );
GreenMail greenMail = new GreenMail ( serverSetup );
greenMail.start ( );
```
After the email is sent I execute the following code:
```
greenMail.waitForIncomingEmail ( 2 );
greenMail.getReceivedMessages();
```

Now when I call `greenMail.getReceivedMessages()` an empty list is returned. 
The line `greenMail.waitForIncomingEmail ( 2 )` calls `SMTPManager.createAndAddNewWaitObject(2)` and that calls `imapHostManager.getAllMessages().size()` and that returns 2.

So greenMail.getReceivedMessages() returns an empty list and mapHostManager.getAllMessages() returns 2 messages. Is this a bug?

Yours sincerly,
Martijn

**Comment by marcelmay** [comment] 2015-08-29 12:21
Hi Martijn,

which version of GreenMail do you use?

I tried to reproduce with current master (1.4.2-SNAPSHOT) using a small test (see below).
Is ```greenMail.waitForIncomingEmail ( 2 );``` returning true?

```
@Rule
public final GreenMailRule greenMail = new GreenMailRule(new ServerSetup[{ServerSetupTest.SMTP});

@Test
public void testSmtpServer2() throws MessagingException {
        GreenMailUtil.sendTextEmailTest("to@localhost.com", "from@localhost.com", "subject-1", "body");
        GreenMailUtil.sendTextEmailTest("to@localhost.com", "from@localhost.com", "subject-2", "body");
        assertTrue(greenMail.waitForIncomingEmail(2));
        MimeMessage[] emails = greenMail.getReceivedMessages();
        assertEquals(2, emails.length);
}
```

**Comment by buildscientist** [comment] 2015-10-02 01:46
Hi @mhiemstrapodiumtv - are you still having issues with this?

**Comment by mhiemstrapodiumtv** [comment] 2015-10-05 07:21
Hi Youssuf,

I haven't had time to test it due to other projects having priority 
above our test project and it's been really busy around here. I hope to 
let you know as soon as possible perhaps this week.

Martijn

**Comment by buildscientist** [comment] 2015-10-16 02:13
@mhiemstrapodiumtv Any updates on this? Can you submit a PR with a unit test?

**Comment by mhiemstrapodiumtv** [comment] 2015-10-16 07:17
Hi Youssuf,

Currently things aren't going well at the company I am working for and I 
will probably leave this company soon. So I won't have any updates on 
this. If no one else has reported something like this then it's probably 
an issue with my code.

Anyhow thanks your time,
Martijn

**Comment by marcelmay** [comment] 2015-10-18 15:24
Closing now as I could not reproduce with my test above.

**Closed by marcelmay** 2015-10-18 15:24 UTC
Labels: invalid
