### ISSUE TITLE
SearchCommandParser, npe, v 1.5.4

### ISSUE THREAD

**Issue by p-ledenev** [greenmail-mail-test/greenmail#202] opened 2017-05-10 11:29 UTC
Line 92 com.icegreen.greenmail.imap.commands.SearchCommandParser
`if (b.expectsParameter() && key.isCharsetAware() && null != charset && next == CHR_SPACE) {`
**b** is still null after
```
SearchKey key = SearchKey.valueOf(keyValue);
 if (SearchKey.NOT == key) {
     negated = true;
 } else {
     b = SearchTermBuilder.create(key);
 }
```

**Comment by marcelmay** [comment] 2017-05-11 05:21
I think this is a duplicate of #201

**Closed by marcelmay** 2017-05-11 05:21 UTC

**Comment by marcelmay** [comment] 2017-05-14 10:40
@p-ledenev , let me know if newest 1.5.5 release still shows the issue - thx!
