### ISSUE TITLE
IllegalStateException while delivering a message via user

### ISSUE THREAD

**Issue by sameepsi** [greenmail-mail-test/greenmail#129] opened 2016-04-21 06:00 UTC
Build Number- 1.5.0

I was using **user.deliver(message)**; to deliver message to the mail box and received following exception.
Cause: java.lang.NullPointerException java.lang.IllegalStateException: Can not deliver javax.mail.internet.MimeMessage@b98a4 for user UserImpl{email='prateek@test', login='prateek@test'}

Digging further in I found that Folder INBOX did not exist for this user prateek@test
While now if I try deleting this user, it says NoSuchFolderExistsException INBOX. What I believe is when I ask green mail to register user it does not do it properly but returns a user which is useless.

I found a work around to this but still needs to fix this asap.

**Comment by buildscientist** [comment] 2016-04-21 06:21
Can you submit a unit test or the exact code you're running?

**Comment by buildscientist** [comment] 2016-04-25 16:06
@sameepsi I wrote a small unit test to try and confirm this issue and was not able to reproduce it: 

``` java
    @Test
    public void testUserDelivery() throws Exception {
        GreenMail greenMail = new GreenMail(ServerSetupTest.ALL);
        /*
          Even with required user authentication disabled calling GreenMailUser.deliver()
          still works greenMail.getManagers().getUserManager().setAuthRequired(false);
       */
        try {
            GreenMailUser greenmailuser = greenMail.setUser("foo@localhost", "pwd");
            greenMail.start();
            MimeMessage message = GreenMailUtil.newMimeMessage(SAMPLE_EMAIL);
            greenmailuser.deliver(message);

        } finally {
            greenMail.stop();
        }

```

Going to close this until you can submit sample code. Feel free to reopen this issue.

**Closed by buildscientist** 2016-04-25 16:06 UTC

**Comment by sameepsi** [comment] 2016-04-26 05:15
@buildscientist 
Hello the issue is not 100% recreatable but it is occuring sometimes. I am posting my code over here.

package greenmailtest;

import java.io.File;
import java.io.IOException;
import java.util.Properties;

import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.URLName;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import com.icegreen.greenmail.user.GreenMailUser;
import com.icegreen.greenmail.user.UserException;
import com.icegreen.greenmail.util.GreenMail;
import com.icegreen.greenmail.util.ServerSetupTest;
 
public class ImapIT {
    private static final String USER_PASSWORD = "abcdef123";
    private static final String USER_NAME = "hascode";
    private static final String EMAIL_USER_ADDRESS = "hascode@localhost";
    private static final String EMAIL_TO = "someone@localhost.com";
    private static final String EMAIL_SUBJECT = "Test E-Mail";
    private static final String EMAIL_TEXT = "This is a test e-mail.";
    private GreenMail mailServer;
 
    
    public  void setUp() {
        mailServer = new GreenMail(ServerSetupTest.IMAP);
        mailServer.start();
    }
 
    
    public void tearDown() {
        mailServer.stop();
    }
 
    
    public void getMails() throws IOException, MessagingException,
    UserException, InterruptedException {
        // create user on mail server
        GreenMailUser user = mailServer.setUser(EMAIL_USER_ADDRESS, USER_NAME,
        USER_PASSWORD);
 
        // create an e-mail message using javax.mail ..
        File file=new File("/home/sameepsinghania/Desktop/prateek1.png");
       // byte[] byteArray=TestMailUtil.readContentIntoByteArray(file);
        MimeMultipart multipart=MailboxSimulatorUtil.createMultipartWithAttachment(EMAIL_TEXT,file, "sameep.png");
        
        MimeMessage message = new MimeMessage((Session) null);
        message.setFrom(new InternetAddress(EMAIL_TO));
        message.addRecipient(Message.RecipientType.TO, new InternetAddress(
        EMAIL_USER_ADDRESS));
        message.setSubject(EMAIL_SUBJECT);
        message.setContent(multipart);
        // use greenmail to store the message
        user.deliver(message);
 
        
        
        Properties props = new Properties();
        Session session = Session.getInstance(props);
        URLName urlName = new URLName("imap", "127.0.0.1",
        ServerSetupTest.IMAP.getPort(), null, user.getLogin(),
        user.getPassword());
        Store store = session.getStore(urlName);
        store.connect();
 
        Folder folder = store.getFolder("INBOX");
        folder.open(Folder.READ_ONLY);
        Message[] messages = folder.getMessages();
        for(Message message1: messages){
        System.out.println("subject "+message1.getSubject());}
    }
    
    public static void main(String[]args){
    	ImapIT imap=new ImapIT();
    	imap.setUp();
    	try {
			imap.getMails();
			//imap.tearDown();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (UserException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }
}

**Comment by sameepsi** [comment] 2016-04-26 05:20
Also sometimes getting this error-:
cause java.lang.NullPointerException
java.lang.IllegalStateException: Can not deliver javax.mail.internet.MimeMessage@184575e for user UserImpl{email='prateek@test', login='prateek@test'}
	at com.icegreen.greenmail.user.UserImpl.deliver(UserImpl.java:67)
	at com.drishti.dacx.client.webaccess.load20.impl.mailbox.UserSimulator.startProcessing(UserSimulator.java:91)
	at com.drishti.dacx.client.webaccess.load20.impl.mailbox.UserSimulator.run(UserSimulator.java:70)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.icegreen.greenmail.store.HierarchicalFolder.getChild(HierarchicalFolder.java:67)
	at com.icegreen.greenmail.store.InMemoryStore.getMailbox(InMemoryStore.java:41)
	at com.icegreen.greenmail.imap.ImapHostManagerImpl.getFolder(ImapHostManagerImpl.java:65)
	at com.icegreen.greenmail.imap.ImapHostManagerImpl.getInbox(ImapHostManagerImpl.java:89)
	at com.icegreen.greenmail.user.UserImpl.deliver(UserImpl.java:65)


After debugging for a while found out in HierarchicalFolder 'children' contains one of the elements as null and whille calling getChildern() there isn't any null check and that null member of the collection is also parsed and hence it's throwing a null pointer exception.
I have 2 questions;

1. Why is there a null element in the collection? And that too sometimes only because most of the times codes runs fine.
2.Why null check was not properly done in the code?

**Comment by buildscientist** [comment] 2016-04-26 06:08
@sameepsi is this code you pasted part of a JUnit test? If so why is your test being called from main()?

As for the null if you're referring to: 
``` java
   public HierarchicalFolder getChild(String name) {
        for (HierarchicalFolder child : children) {
            if (child.getName().equalsIgnoreCase(name)) {
                return child;
            }
        }
        return null;
    }
```
Returning null in this case is valid if there are no child folders found.

**Comment by buildscientist** [comment] 2016-04-26 07:18
@sameepsi your code example is missing this: 

``` java
    MimeMultipart multipart=MailboxSimulatorUtil.createMultipartWithAttachment(EMAIL_TEXT,file, "sameep.png");
```

Additionally how can we debug this when we don't have the rest of the code referenced in your stack trace? 

``` java

com.drishti.dacx.client.webaccess.load20.impl.mailbox.UserSimulator.startProcessing(UserSimulator.java:91)
at com.drishti.dacx.client.webaccess.load20.impl.mailbox.UserSimulator.run(UserSimulator.java:70)
```

**Comment by sameepsi** [comment] 2016-04-26 08:05
public HierarchicalFolder getChild(String name) {
        for (HierarchicalFolder child : children) {
            if (child.getName().equalsIgnoreCase(name)) {
                return child;
            }
        }
        return null;
    }

here children is a collection right and sometime it contains a **null** element and when you do child.getName(), the code will break, that's what I am saying either you should not allow null entry in children or null check should be mandated.

**Comment by sameepsi** [comment] 2016-04-26 08:20
package com.drishti.ameyo.mailbox.simulator.impl;

	import greenmailtest.MailboxSimulatorUtil;

	import java.io.File;
	import java.util.Calendar;
	import java.util.Random;

	import javax.mail.Message;
	import javax.mail.MessagingException;
	import javax.mail.Session;
	import javax.mail.internet.AddressException;
	import javax.mail.internet.InternetAddress;
	import javax.mail.internet.MimeMessage;
	import javax.mail.internet.MimeMultipart;

	import com.drishti.ameyo.mailbox.simulator.UserConfiguration;
	import com.drishti.ameyo.mailbox.simulator.api.ISimulator;
	import com.icegreen.greenmail.user.GreenMailUser;
	import com.icegreen.greenmail.util.GreenMailUtil;

	public class UserSimulator implements ISimulator, Runnable {

	private MailboxSimulator mailboxSimulator;
	private UserConfiguration userConfiguration;
	private GreenMailUser user;
	private int mailCount;
	private int fetchIntervalInSeconds;
	private int mailsSent=0;
	private int totalMailsToSend;
	private boolean keeprunning;
	private boolean randomSubject=true;
	private boolean randomFrom=true;
	private boolean sendAttachment=false;
	private String attachmentsPath;
	private String[]attachment_file_names;
	private String []fromMailIds;
	private String[]subjects;
	private int mailsWithAttachmentsSent;


	public UserSimulator(MailboxSimulator mailboxSimulator,UserConfiguration userConfiguration){
		this.mailboxSimulator=mailboxSimulator;
		this.userConfiguration=userConfiguration;
		this.mailCount=userConfiguration.getMailCount();
		this.fetchIntervalInSeconds=userConfiguration.getFetchInterval();
		this.totalMailsToSend=userConfiguration.getTotalMailCount();
		if(userConfiguration.getFromMailIds()!=null && userConfiguration.getFromMailIds().length>0){
			randomFrom=false;
			fromMailIds=userConfiguration.getFromMailIds();
		}
		if(userConfiguration.getSubjects()!=null && userConfiguration.getSubjects().length>0){
			randomSubject=false;
			subjects=userConfiguration.getSubjects();
		}
		if(userConfiguration.getAttachmentFileName()!=null & userConfiguration.getAttachmentFileName().length>0){
			sendAttachment=true;
			attachmentsPath=userConfiguration.getAttachmentsPath();
			attachment_file_names=userConfiguration.getAttachmentFileName();
		}
	}

	@Override
	public void run() {
		registerUser();
		startProcessing();
	}

	private void startProcessing() {
		while(keeprunning){
			try {
				int mailsToThrow=getMailsToThrow();
				for(int i=0;i<mailsToThrow;i++){
					String subject=getSubject();
					String body=GreenMailUtil.random(1000);
					MimeMessage message = new MimeMessage((Session) null);
					message.setFrom(new InternetAddress(getFromAddress()));
					message.addRecipient(Message.RecipientType.TO, new InternetAddress(
							userConfiguration.getUserid()));
					message.setSubject(subject);
					File file=getFile();
					MimeMultipart multipart=MailboxSimulatorUtil.createMultipartWithAttachment(body,file,file!=null?file.getName():null);
					message.setText(body);
					message.setContent(multipart);
					if(mailboxSimulator.isServerRunning() && !mailboxSimulator.getServerInShuttingDownMode()){
						try{
							user.deliver(message);// this is the place where i get exception
							mailsSent++;

						}catch(Exception e){
							System.out.println("Cause: "+e.getCause()+"  "+e.getMessage()+" "+e);
							if(e.getCause()!=null && e.getCause() instanceof NullPointerException){
								reRegisterUser();
							}

						}
					}
					else{
						waitForServerToGetUp();
						try{
							user.deliver(message);// this is the place where i get exception
							mailsSent++;
						}catch(Exception e){
							System.out.println("Cause: "+e.getCause()+"  "+e.getMessage()+" "+e);
							if(e.getCause()!=null && e.getCause() instanceof NullPointerException){
								registerUser();
							}

						}

					}

				}
				System.out.println("Total mails sent so far for userid: "+userConfiguration.getUserid()+" is "+mailsSent
						);
				System.out.println("Total mails sent so far with attachment  for userid: "+userConfiguration.getUserid()+" is "
						+mailsWithAttachmentsSent);

				if(mailsSent<totalMailsToSend){
					Thread.sleep((fetchIntervalInSeconds)*1000);
				}
				else{
					keeprunning=false;
					System.out.println("Total mails sent for user id: "+userConfiguration.getUserid()+" are "+ mailsSent+
							" at "+Calendar.getInstance().getTime());
					System.out.println("Total mails sent with attachments for user id: "+userConfiguration.getUserid()+" are "+ mailsWithAttachmentsSent+
							" at "+Calendar.getInstance().getTime());
				}
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (AddressException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (MessagingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	private void reRegisterUser() {
		mailboxSimulator.deleteUser(user);
		registerUser();
	}

	private File getFile() {
		File file=null;
		if(sendAttachment){

			Random random=new Random();
			boolean toSend=random.nextBoolean();
			if(toSend){
				int index=random.nextInt(attachment_file_names.length);
				String fileName=attachment_file_names[index];
				file=new File(attachmentsPath+fileName);
				if(!file.exists()){
					System.out.println("No file exists with name: "+fileName+" at path: "+attachmentsPath);
					return null;
				}
				mailsWithAttachmentsSent++;
			}
		}
		return file;
	}

	private String getFromAddress() {
		if(randomFrom){
			String from=GreenMailUtil.random(14);
			from=from+"@"+GreenMailUtil.random(5)+".com";
			return from;
		}
		Random random=new Random();
		int index=random.nextInt(fromMailIds.length);
		return fromMailIds[index];
	}

	private String getSubject() {
		if(randomSubject){
			return GreenMailUtil.random(30);
		}
		Random random=new Random();
		int index=random.nextInt(subjects.length);
		return subjects[index];
	}

	private void waitForServerToGetUp() {

		System.out.println("Mail Server is going down so user "+ userConfiguration.getUserid()+" will wait untill server restarts");
		try {
			synchronized (mailboxSimulator) {
				mailboxSimulator.wait();
			}
			if(!mailboxSimulator.isServerRunning()){
				mailboxSimulator.startServer();
			}
			user=mailboxSimulator.registerUser(userConfiguration.getUserid(), userConfiguration.getPassword());
			System.out.println("Server is up now so user "+userConfiguration.getUserid()+" will continue it's work");
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private int getMailsToThrow() {
		int mailsToThrow=mailCount;
		if(userConfiguration.getMailCountRandom()){
			Random random=new Random();
			mailsToThrow=random.nextInt(mailCount);
		}
		System.out.println("total mails to throw for userid: "+userConfiguration.getUserid()+" is "+mailsToThrow);
		return mailsToThrow;
	}

	private void registerUser() {
		user=mailboxSimulator.registerUser(userConfiguration.getUserid(), userConfiguration.getPassword());
		keeprunning=true;
	}


}
 
This is my original code

Cause: java.lang.NullPointerException  Can not deliver javax.mail.internet.MimeMessage@93b488 for user UserImpl{email='prateek@test', login='prateek@test'} java.lang.IllegalStateException:
Caused by: java.lang.NullPointerException
at com.icegreen.greenmail.store.HierarchicalFolder.getChild(HierarchicalFolder.java:67)
at com.icegreen.greenmail.store.InMemoryStore.getMailbox(InMemoryStore.java:41)
at com.icegreen.greenmail.imap.ImapHostManagerImpl.getFolder(ImapHostManagerImpl.java:65)
at com.icegreen.greenmail.imap.ImapHostManagerImpl.getInbox(ImapHostManagerImpl.java:89)
at com.icegreen.greenmail.user.UserImpl.deliver(UserImpl.java:65)

this is the exception i get.

**Comment by sameepsi** [comment] 2016-04-29 09:26
any updates on this?? As I am continuously facing this issue.
