### ISSUE TITLE
Fix Travis CI OpenJDK 6 / Maven build

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#69] opened 2015-04-28 09:13 UTC
Travis CI recently upgraded their Maven version to 3.3.1, which breaks with JDK 6.

1. Custom install Maven 3.2.x 
2. Re-enable JDK 1.6 build

**Comment by buildscientist** [comment] 2015-05-09 20:00
I think this is related to issue #23 

I've looked at the [Java specific feature set](https://circleci.com/docs/environment#java) in CircleCI and I think this fits our requirements. 

I understand that Java 6/7 have both been discontinued but a large number of companies will purchase Oracle support contracts to extend backported bug fixes for those versions. 

We should propose dropping support for Java 6/7 in GreenMail v2.0 - once we complete development of the test API.

**Comment by buildscientist** [comment] 2015-06-08 16:53
Still working on getting CircleCI configured on my branch. They appear to have some bugs associated with running parallel builds on different versions of the JDK. On a positive note - their tech support is helping me craft a custom circle.yml file

**Comment by buildscientist** [comment] 2015-06-10 01:14
At this point I'm not sure if CircleCI supports simultaneous builds across different versions of the JDK. Still working through the details with CircleCI support. We might need to stick with Travis.

**Comment by buildscientist** [comment] 2015-06-10 01:32
Never mind - looks like I got it to work. A lot of these cloud CI providers use these yucky declarative config files to setup build workflows :-1:  

I'll need to clean it up - but here's what I've got so far: 

```yaml
general:
 build_dir: ./

test:
 override:
 - sudo update-alternatives --set java "/usr/lib/jvm/jdk1.7.0/bin/java"
 - sudo update-alternatives --set javac "/usr/lib/jvm/jdk1.7.0/bin/javac"
 - mvn install -DskipTests
 - mvn test
 - sudo update-alternatives --set java "/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java"
 - sudo update-alternatives --set javac "/usr/lib/jvm/java-7-openjdk-amd64/bin/javac"
 - mvn clean install -DskipTests
 - mvn test
```

I am noticing that some of the tests aren't shutting down the GreenMail service properly so I'll need to go in there and clean those up.

**Comment by camann9** [comment] 2015-06-10 05:40
Awesome, thanks

**Comment by marcelmay** [comment] 2015-06-10 06:27
"some of the tests aren't shutting down" => can you get me a stacktrace? Is there any way to reproduce this? Thx alot!

**Comment by buildscientist** [comment] 2015-06-14 05:56
@marcelmay I haven't been able to reproduce this issue but I'll debug this further when/if I'm able to. 

The CircleCI config is ready to go. We just need an official greenmail organization account on CircleCI to setup builds. 

After that I can add the CircleCI build badge and remove the TravisCI config.

**Comment by marcelmay** [comment] 2015-06-14 09:03
@buildscientist Thanks - I just [fixed](https://github.com/greenmail-mail-test/greenmail/commit/3e0d411666034979d355ee665fcd79cdd96a3f5b) another issue when stopping GreenMail . This can occur when quickly starting/stopping GreenMail. Maybe that was it.

Lets keep an eye on start/stop issues!

**Comment by buildscientist** [comment] 2015-06-22 02:52
@camann9 @marcelmay can I close this issue out? We're still running on TravisCI. 

I'm not an admin on this repo/org so I can't add it to CircleCI.

**Comment by camann9** [comment] 2015-06-22 10:26
I'm fixing it today :-) . finally I have time

**Comment by buildscientist** [comment] 2015-06-22 11:42
Cool thanks. @marcelmay looks like we're still running into that issue where the ServerStartUp port is not being released properly. I can look into this later today. 
Do we want to back out the last merge until this is resolved?

**Comment by camann9** [comment] 2015-06-22 11:44
I'm looking at it now (once my IDE is set up again....)

**Comment by camann9** [comment] 2015-06-22 11:54
This seems to be some problem associated with running on Circle (or on
linux). On my Windows machine the build+test runs in 10 secs without error.

Christian Amann <camann9@gmail.com> schrieb am Mo., 22. Juni 2015 um
13:43 Uhr:

**Comment by camann9** [comment] 2015-06-22 14:24
I sadly have to get some other suff done today. I'll see if I can do
something about those failures. I think it tkaes some playing around to
find out which test doesn't deallocate its port and why it doesn't.

Christian Amann <camann9@gmail.com> schrieb am Mo., 22. Juni 2015 um
13:54 Uhr:

**Comment by camann9** [comment] 2015-06-22 15:46
Ok, this seems to be not very reproducible. I Ignored some tests and ran the build and it worked. Then I removed all ignores and ran the build again and it failed. Then I reverted to the state with some ignores and it failed again. The behaviour is very strange. Maybe someone else can look into it. I'm gonna re-enable all tests again.

**Comment by camann9** [comment] 2015-06-22 15:50
See build https://circleci.com/gh/greenmail-mail-test/greenmail/15 . Some test runs work, some not. The runs are with different JVMs but that shouldn't have any influence. AFAIK they just fail/pass randomly.

**Comment by marcelmay** [comment] 2015-06-22 18:21
I suspect an issue with stopping GreenMail (so the next test will not able to bind to port). I'll enable full debug, so we can better see what's going on.

**Comment by marcelmay** [comment] 2015-06-22 18:25
Also, we should maybe experiment on a test branch ... ?

**Comment by buildscientist** [comment] 2015-06-22 18:25
@marcelmay You can ssh into the box that runs the actual test - hit the "Debug SSH" button to redo the build and you'll be able to login with your GitHub SSH key.

**Comment by marcelmay** [comment] 2015-06-22 18:26
Thx!

**Comment by buildscientist** [comment] 2015-06-22 18:30
@marcelmay Sure - CircleCI supports running builds against branches. Note: We can only have 1 build run against a code-line at a time.

**Comment by camann9** [comment] 2015-06-22 19:14
Yeah, I was thinking about creating a separate branch but then I thought it
would be resolved faster. Seems like it isn't...

**Comment by buildscientist** [comment] 2015-06-24 12:26
@camann9 @marcelmay I think I figured out what might be causing this issue - but I'm still working on refactoring DummySSLServerSocketFactory to get this to work - have a look at f351b4fd123750b0c73f335b9a50f52d0c954588 and 62ebb8b0295e3a279142aef512e3295096dcd552 for an idea of what I'm trying to do.

**Comment by marcelmay** [comment] 2015-06-24 18:46
Looks interesting - any success so far?

Would be interesting to see the still open connections and their state when the issue occurs...

Cheers,
Marcel

**Comment by buildscientist** [comment] 2015-06-24 19:28
Not really - I need to write a unit test for this so I'm not having to rely on a CircleCI builds to reproduce the issue.

**Comment by buildscientist** [comment] 2015-06-30 00:48
One thing I'm considering doing is looking into why the tests create serversockets on the same ports each time the test runs. Shouldn't those be randomized to run anything above >1024 ? 

If we're running into TIME_WAIT situation we can temporarily get around this by running on randomized ports for each test run.

**Comment by marcelmay** [comment] 2015-07-17 18:48
@buildscientist : Your idea with setReuseAddress worked for my pull request (successful build) but failed when merged... my fault.

**Comment by buildscientist** [comment] 2015-07-18 23:40
So we have an outstanding issue where every other build fails. It looks like CircleCI uses Docker to run the builds. I am working with the support team to see if the container can be restarted between every mvn test run to flush TCP connection tables. 

Test wise I am unable to reproduce this. @marcelmay and I spent some time debugging this and looking into kernel parameters but if CircleCI is running Docker - sysctl parameters won't make any difference.

**Comment by buildscientist** [comment] 2015-07-21 16:27
Added   - sudo sysctl net.netfilter.nf_conntrack_tcp_timeout_time_wait=1 to the circle.yml config on my issue-23 branch and I'm still running into the same issue. 

CircleCI support stated the following: 

```
Looking at your build, it looks like the first "mvn test" is starting a bunch of servers that aren't being shut down, so when the second "mvn test" runs and tries to start up servers it fails with the error you're seeing because the port it wants to start them on is already in use. 

You are not using docker - for information on how to configure that, please see:
https://circleci.com/docs/docker
```

I am going to rewrite the circle.yml to run one test and see about debugging the issue further. It doesn't look like the call to SocketServer.setReuseAddress(true) is being honored. @marcelmay and I still saw a large number of TIME_WAIT in the TCP connection table on the CircleCI node.  

One other area I'd like to look into is the bind address logic in ServerSetup. I see that we're setting this to 0.0.0.0 (gateway address) but I have a sneaky suspicion that maybe it's not acting like as such on the CircleCI box.

**Comment by marcelmay** [comment] 2015-07-27 20:47
I can reproduce the issue on docker on my Mac now.

@buildscientist : Tests run on 127.0.0.1, AFAIK

**Comment by buildscientist** [comment] 2015-08-14 01:52
@marcelmay Can you export your docker config? 

At this point I'm wondering whether or not we should continue using CircleCI - as we're blocking open PR's :-1:

**Comment by marcelmay** [comment] 2015-08-21 22:13
@buildscientist Strange now everything works in Docker (see https://gist.github.com/marcelmay/c344ff8d17fea79d3df6)

**Comment by buildscientist** [comment] 2015-08-21 22:24
@marcelmay The gist references oracle jdk 7. Have you run this on CircleCI or just locally?

**Comment by buildscientist** [comment] 2015-09-26 20:24
Closing this issue as builds are now stable on CircleCI.

**Closed by buildscientist** 2015-09-26 20:24 UTC
Labels: enhancement
