### ISSUE TITLE
IMAP fails to fetch message when content type is text/html

### ISSUE THREAD

**Issue by granby** [greenmail-mail-test/greenmail#172] opened 2017-01-02 15:19 UTC
This code fails when content type is text/html in imap/commands/FetchCommand.java (handleBodyFetch):

`if (contentType.toLowerCase().startsWith("text/plain") && "1".equals(sectionSpecifier)) {
                handleBodyFetchForText(mimeMessage, partial, response);
 } else {
                MimeMultipart mp = (MimeMultipart) mimeMessage.getContent();
                BodyPart part = null;`

Content in this case is a String and you get a class cast exception.

**Comment by marcelmay** [comment] 2017-01-02 15:47
@granby  : do you have a test for us? Otherwise, I'll try to reproduce it with my own test.

**Comment by granby** [comment] 2017-01-02 15:53
No, sorry. If you have any problem reproducing it I'll gladly help.

**Comment by granby** [comment] 2017-01-02 15:55
This thread could be helpful: http://stackoverflow.com/questions/13331989/how-to-handle-multipart-alternative-mail-with-javamail

**Comment by marcelmay** [comment] 2017-01-03 08:35
Multipart/alternative with a text/plain and text/html part works.

But sending a forwarded multipart/alternative fails:
```
ClassCastException: javax.mail.internet.MimeMessage cannot be cast to javax.mail.Multipart
	at com.icegreen.greenmail.imap.commands.FetchCommand.handleBodyFetch(FetchCommand.java:242)
```

So I have a test case now for reproducing the issue.

**Comment by gusran** [comment] 2017-01-03 12:10
Ok! Just to avoid misunderstanding; this is an email that the client (Rainloop) could not fetch via IMAP (class cast exception in Greenmail - String cannot be cast to Multipart):

Return-Path: <donotReply@somedomain.com>
Received: from 10.55.101.48 (HELO somehost.net); Mon Jan 02 16:10:15 CET 2017
Date: Mon, 2 Jan 2017 16:10:15 +0100 (CET)
From: donotReply@somedomain.com
To: receiver@somedomain.com
Message-ID: <1696159807.86.1483369815766.sonia>
Subject: =?UTF-8?Q?Subject?=
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable


<!DOCTYPE html "-//w3c//dtd xhtml 1.0 transitional //en" "http://www.w3.org=
/tr/xhtml1/dtd/xhtml1-transitional.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml">
<head> etc...

**Comment by marcelmay** [comment] 2017-01-03 12:21
@gusran, @granby : Can you forward me the problematic email, as an attachment?

You are using latest GreenMail 1.5.2?

**Comment by gusran** [comment] 2017-01-03 12:54
Yes

**Comment by gusran** [comment] 2017-01-03 13:03
[problematic.txt](https://github.com/greenmail-mail-test/greenmail/files/682251/problematic.txt)

I played around with your test code a little, and I failed to reproduce it since sectionSpecifier gets set to TEXT, but when rainloop fetches it is appearantly set to 1.

And yes, I use 1.5.2.

**Comment by gusran** [comment] 2017-01-03 14:07
Here are the logs from GreenMail and Rainloop:

[greenmail.txt](https://github.com/greenmail-mail-test/greenmail/files/682346/greenmail.txt)
[rainloop.txt](https://github.com/greenmail-mail-test/greenmail/files/682347/rainloop.txt)

This is my quick fix (imap.commands.FetchCommand/handleBodyFetch):

`Object content = mimeMessage.getContent();
            if (content instanceof String && "1".equals(sectionSpecifier)) {
                handleBodyFetchForText(mimeMessage, partial, response);
            } else if (content instanceof MimeMultipart) {`

**Comment by marcelmay** [comment] 2017-01-08 18:48
Just fixed #178, where GreenMail received a NPE when receiving a forwarded message.

**Comment by marcelmay** [comment] 2017-01-08 19:47
Thanks alot, issue should be fixed now.

Just uploaded a new [1.6.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen) and pushed [greenmail/standalone:1.6.0-SNAPSHOT](https://hub.docker.com/r/greenmail/standalone/tags/) docker image.

I tested GreenMail with this [Rainloop docker image](https://hub.docker.com/r/solidnerd/rainloop/).

**Closed by marcelmay** 2017-01-08 19:47 UTC
Labels: bug

**Comment by gusran** [comment] 2017-01-09 09:13
Thank you! I tested with your published snapshot and it seems to work fine!
